# Generated by Django 5.2 on 2025-05-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_options_item_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockentry',
            old_name='timestamp',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='stockexit',
            old_name='timestamp',
            new_name='date_removed',
        ),
    ]
